#######################
# set env
#######################

DEFAULT_TOOLCHAIN:=arm-none-eabi-
TOOLCHAIN?=${DEFAULT_TOOLCHAIN}

#######################
# load modules
#######################

include ../.comm/base.mk

#######################
# other local commands
#######################
