#######################
# set env
#######################

DEFAULT_TOOLCHAIN:=riscv32-unknown-elf-
TOOLCHAIN?=${DEFAULT_TOOLCHAIN}

#######################
# load modules
#######################

include ../.comm/base.mk

#######################
# other local commands
#######################
